[package]
name = "rustyray"
version = "0.1.0"
authors = ["kasper"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
glfw = "*"
gl = "*"
stb_image = "*"
cgmath = { version = "*", features = ["swizzle"] }
